In [1]:
import cellestial as cl
import scanpy as sc

from lets_plot import *

LetsPlot.setup_html()

data = sc.read_h5ad("data/pbmc3k_pped.h5ad")

In [2]:
import cellestial as cl
import scanpy as sc

from lets_plot import *

LetsPlot.setup_html()

violin = (
    cl.violin(
        data,
        "CD14",
        fill="cell_type_lvl1",
        scale="width",
        point_size=2,
        threshold=0.1,
        trim=False,
    )
    + ggsize(800, 400)
    + scale_fill_brewer(palette="Set2")
    + guides(fill=guide_legend(ncol=2))
)

violin

In [3]:
import cellestial as cl
import scanpy as sc

from lets_plot import *

LetsPlot.setup_html()

violin = (
    cl.violin(
        data,
        "pct_counts_in_top_50_genes",
        fill="cell_type_lvl1",
        scale="width",
        point_size=1,
    )
    + ggsize(800, 400)
    + scale_fill_brewer(palette="Set2")
    + guides(fill=guide_legend(ncol=2))
)

violin

In [4]:
import cellestial as cl
import scanpy as sc

from lets_plot import *

LetsPlot.setup_html()

violin = (
    cl.violin(
        data,
        "pct_counts_in_top_50_genes",
        fill="cell_type_lvl1",
        scale="width",
        show_points=False,
    )
    + ggsize(800, 400)
    + scale_fill_brewer(palette="Set2")
    + guides(fill=guide_legend(ncol=2))
)

violin

In [5]:
violin = (
    cl.violin(
        data,
        ["pct_counts_in_top_200_genes", "n_genes_by_counts"],
        fill="cell_type_lvl1",
        trim=False,
        scale="width",
        point_size=0.6,
        point_alpha=0.4,
        tooltips=["cell_type_lvl1"],
        point_geom="jitter",
    )
    + scale_y_log10()
    + ggsize(800, 400)
)
violin

In [6]:
cl.retrieve(violin)

shape: (30_548, 3)
┌────────────────┬─────────────────────────────┬───────────┐
│ cell_type_lvl1 ┆ variable                    ┆ value     │
│ ---            ┆ ---                         ┆ ---       │
│ cat            ┆ str                         ┆ f64       │
╞════════════════╪═════════════════════════════╪═══════════╡
│ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 69.744892 │
│ Monocytes      ┆ pct_counts_in_top_200_genes ┆ 52.376877 │
│ Erythroid      ┆ pct_counts_in_top_200_genes ┆ 70.386266 │
│ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 48.901701 │
│ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 77.477477 │
│ …              ┆ …                           ┆ …         │
│ Lymphocytes    ┆ n_genes_by_counts           ┆ 227.0     │
│ Lymphocytes    ┆ n_genes_by_counts           ┆ 277.0     │
│ Monocytes      ┆ n_genes_by_counts           ┆ 3797.0    │
│ Lymphocytes    ┆ n_genes_by_counts           ┆ 379.0     │
│ Lymphocytes    ┆ n_genes_by_counts           ┆ 1599.0    │
└────────────────┴─────────────────────────────┴───────────┘

In [7]:
cl.get_mapping(violin)

{'x': 'variable', 'y': 'value', 'fill': 'cell_type_lvl1'}

In [8]:


boxplot = (
    cl.boxplot(
        data,
        "CD14",
        fill="cell_type_lvl1",
        point_size=2,
        threshold=0.1,
    )
    + ggsize(800, 400)
    + scale_fill_brewer(palette="Set2")
    + guides(fill=guide_legend(ncol=2))
)

boxplot

In [9]:
cl.retrieve(boxplot)

shape: (1_511, 3)
┌────────────────┬──────────┬──────────┐
│ cell_type_lvl1 ┆ variable ┆ CD14     │
│ ---            ┆ ---      ┆ ---      │
│ cat            ┆ str      ┆ f32      │
╞════════════════╪══════════╪══════════╡
│ Monocytes      ┆ CD14     ┆ 0.375316 │
│ Lymphocytes    ┆ CD14     ┆ 1.490406 │
│ Monocytes      ┆ CD14     ┆ 0.835762 │
│ Monocytes      ┆ CD14     ┆ 1.359606 │
│ Lymphocytes    ┆ CD14     ┆ 2.508945 │
│ …              ┆ …        ┆ …        │
│ Monocytes      ┆ CD14     ┆ 1.277704 │
│ Monocytes      ┆ CD14     ┆ 1.713763 │
│ Monocytes      ┆ CD14     ┆ 0.902225 │
│ Monocytes      ┆ CD14     ┆ 0.468242 │
│ Monocytes      ┆ CD14     ┆ 1.589272 │
└────────────────┴──────────┴──────────┘

In [10]:
violin.as_dict()

{'data': shape: (30_548, 3)
 ┌────────────────┬─────────────────────────────┬───────────┐
 │ cell_type_lvl1 ┆ variable                    ┆ value     │
 │ ---            ┆ ---                         ┆ ---       │
 │ cat            ┆ str                         ┆ f64       │
 ╞════════════════╪═════════════════════════════╪═══════════╡
 │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 69.744892 │
 │ Monocytes      ┆ pct_counts_in_top_200_genes ┆ 52.376877 │
 │ Erythroid      ┆ pct_counts_in_top_200_genes ┆ 70.386266 │
 │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 48.901701 │
 │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 77.477477 │
 │ …              ┆ …                           ┆ …         │
 │ Lymphocytes    ┆ n_genes_by_counts           ┆ 227.0     │
 │ Lymphocytes    ┆ n_genes_by_counts           ┆ 277.0     │
 │ Monocytes      ┆ n_genes_by_counts           ┆ 3797.0    │
 │ Lymphocytes    ┆ n_genes_by_counts           ┆ 379.0     │
 │ Lymphocytes    ┆ n_genes_by_counts           ┆ 1599.0    │
 └────────────────┴─────────────────────────────┴───────────┘,
 'mapping': {},
 'data_meta': {'series_annotations': [{'type': 'str',
    'column': 'cell_type_lvl1'},
   {'type': 'str', 'column': 'variable'},
   {'type': 'float', 'column': 'value'}]},
 'theme': {'name': 'classic',
  'text': {'color': '#1f1f1f', 'family': 'Arial', 'blank': False},
  'title': {'color': '#1f1f1f', 'family': 'Arial', 'blank': False},
  'axis_title_x': {'blank': True},
  'legend_title': {'color': '#1f1f1f',
   'family': 'Arial',
   'face': 'Bold',
   'blank': False}},
 'ggsize': {'width': 800, 'height': 400},
 'kind': 'plot',
 'scales': [{'aesthetic': 'fill', 'scale_mapper_kind': 'color_hue'},
  {'aesthetic': 'y', 'trans': 'log10'}],
 'layers': [{'geom': 'violin',
   'mapping': {'x': 'variable', 'y': 'value', 'fill': 'cell_type_lvl1'},
   'tooltips': {'formats': [],
    'variables': ['cell_type_lvl1', 'variable', 'value']},
   'data_meta': {},
   'scale': 'width',
   'trim': False,
   'color': '#2f2f2f'},
  {'geom': 'jitter',
   'data': shape: (30_548, 3)
   ┌────────────────┬─────────────────────────────┬───────────┐
   │ cell_type_lvl1 ┆ variable                    ┆ value     │
   │ ---            ┆ ---                         ┆ ---       │
   │ cat            ┆ str                         ┆ f64       │
   ╞════════════════╪═════════════════════════════╪═══════════╡
   │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 69.744892 │
   │ Monocytes      ┆ pct_counts_in_top_200_genes ┆ 52.376877 │
   │ Erythroid      ┆ pct_counts_in_top_200_genes ┆ 70.386266 │
   │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 48.901701 │
   │ Lymphocytes    ┆ pct_counts_in_top_200_genes ┆ 77.477477 │
   │ …              ┆ …                           ┆ …         │
   │ Lymphocytes    ┆ n_genes_by_counts           ┆ 227.0     │
   │ Lymphocytes    ┆ n_genes_by_counts           ┆ 277.0     │
   │ Monocytes      ┆ n_genes_by_counts           ┆ 3797.0    │
   │ Lymphocytes    ┆ n_genes_by_counts           ┆ 379.0     │
   │ Lymphocytes    ┆ n_genes_by_counts           ┆ 1599.0    │
   └────────────────┴─────────────────────────────┴───────────┘,
   'mapping': {'x': 'variable', 'y': 'value', 'fill': 'cell_type_lvl1'},
   'position': {'name': 'jitterdodge', 'dodge_width': 0.95},
   'tooltips': {'formats': [], 'variables': ['cell_type_lvl1']},
   'data_meta': {'series_annotations': [{'type': 'str',
      'column': 'cell_type_lvl1'},
     {'type': 'str', 'column': 'variable'},
     {'type': 'float', 'column': 'value'}]},
   'color': '#1f1f1f',
   'alpha': 0.4,
   'size': 0.6}],
 'metainfo_list': []}